# Minimal Makefile for generating Markdown readmes

cmd_readme:
	@echo Generating Markdown README of MixCli commands in command_readme.md with mixcli.util.cmd_readme module
	PYTHONPATH=../src python -m mixcli.util.cmd_readme -t md -o command_readme.md